class QuestionUtil{

  static final List<String> funQuestions = [
    "Sevgilin 30 cm mi olsun yoksa 4.5 metre mi?",
    "Elin kadar büyük kulakların mı olsun isterdin yoksa kulakların kadar küçük ellerin mi?",
    "Ters dönmüş ellerin mi olsun isterdin yoksa ters dönmüş ayakların mı?",
    "Her yemek yediğinde tadını alabileceğin ama hiç doymayacağın şekilde yemek mi yoksa her içtiğin suyun tuzlu olması mı?",
    "Hayatını kurtarmak için ya sevgilin arkadaşınla öpüşecek ya sen arkadaşınla hangisi?",
    "Hayalindeki işi yapacaksın ama her sabah işe gitmeden önce 1 saat durmadan kavunlu nargile içeceksin kabul mü?",
    "10 yıllık sevgilinle düğününüzden bir gün önce sevgilinin annesinin sevgilini emzirdiğini gördün, evlenmekten vazgeçer misin?",

  ];

  static final List<String> groupQuestions = [
    "Grubun en maceraperesti kim?",
    "Bir gün boyunca kim sosyal medyadan uzak kalamazdı?",
    "Grubun en rahat insanı kimdir?",
    "Kim uzun bir yolculukta arabada DJ olurdu?",
    "Kim en beklenmedik şeyleri hatırlar?",
    "Kim her durumda pozitif kalmayı başarır?",
    "Kim herkese moral verebilecek kadar motive edicidir?",
    "Grubun en komiği kim?",
    "Bir adada mahsur kalsanız, kimin hayatta kalma rehberliğine güvenirdiniz?",
    "Kim tatlılar konusunda en büyük gurmedir?",
    "Grubun en meraklısı kim?",
    "Grubun en büyük doğa tutkunu kimdir?",
    "Kim film ve dizi önerileri konusunda bir uzman?",
    "Kim grubun en ilginç hobilerine sahip kişisi?",
    "Kim evde bir tamirat işini halledebilir?",
    "Kim gruptaki en rasyonel kararları verebilir?",
    "Grubun en duygusalı kim?",
    "Grubun her yere en geç kalanı kim?",
    "Kim en çok beş dakikaya oradayım demiştir ama en az 30 dakika sonra gelmiştir?",
    "Kim bir daha yapmam dediği şeyi yine yapar?",
    "Kim sohbette her zaman konuyu bambaşka bir yere taşır?",
    "Kim buluşmaları hep sektirir?",
    "Kim en çok başkalarının yiyecek/içeceğine sulanır?",
    "Grubun en kararsızı kim?",


  ];

  static final List<String> seriousQuestions = [
    "Hayatın bir kasette olsa hangi anını izlemek isterdin?",
    "Tanıdığın herkesi unutmak mı yoksa tanıdığın herkes tarafından unutulmak mı?",
    "Ömrünün sonuna kadar sadece bir anı hatırlayabilecek olsaydın, hangi anıyı seçerdin ve neden?",
    "Bir kitabın veya filmin içinde yaşayacak olsaydın, hangisini seçerdin ve neden?",
    "30 yaşına kadar harika bir hayat yaşamak mı yoksa 80 yaşına kadar standart, huzurlu bir hayat yaşamak mı?",
    "Çocukluğundan kalma bir alışkanlığın var mı?",
    "Birini hiç kazanamamış olmak mı yoksa sonsuza kadar kaybetmek mi?",
    "10 yıl önceki haline bir tavsiye versen bu ne olurdu?",
    "Biri ne yaparsa hemen ondan soğursun?",
    "Hapse girseydin tanıdıkların bunun ne için olduğunu düşünürdü?",
    "En büyük korkun ne?",
    "En güvende hissettiğin yer neresi?",
    "Ebeveynlerinizi mi birbirini aldatırken yakalamak? yoksa sevgilinizi mi sizi aldatırken yakalamak?",
    "En sevdiğin şarkıcı/grup bir şarkı söylemek için mikrofonu sana uzattı hangi şarkıyı söylüyorsunuz?",
    "Bir ömür boyu istediğin bir şehirde yaşamak zorunda olsan, hangi şehri seçerdin ve neden?",
    "Sevgilinin senin hayatını kurtarması için seni aldatması gerekiyor kabul eder misin?",
    "Hayatında en büyük fedakarlığı ne zaman ve neden yaptın?",
    "Ebeveynlerinden aldığın en önemli hayat dersini paylaşır mısın?",
    "Geçmişte yaptığın hangi hatayı düzeltmek isterdin ve bu hata sana ne öğretti?",
    "Hayatında ilham aldığın bir kişi veya karakter var mı? Onun hangi özellikleri seni etkiledi?",
    "Hayatında karşılaştığın en büyük ahlaki ikilem neydi ve bu ikilemi nasıl çözdün?",
    "Nasıl öleceğini bilmek mi? Yoksa ne zaman öleceğini bilmek mi?",
    "Bir ömür boyu sadece bir duyunu kaybetmek zorunda olsan, hangisini seçerdin ve neden?",
    "Bir vahşi hayvanı evcilleşitirebilme şansın olsa bu hangisi olurdu?",
    "Her gün günde 15 saat uyumak mı? yoksa 3 saat uyumak mı?",
    "Aile, aşk, para, sağlık arasında sıralaman ne olurdu?",
    "Hiçbir maddi kaygın olmasaydı hangi işi yapmak isterdin?",
    "Hayatının kalanını seçtiğin 3 kişi ile yaşamak zorundasın kimleri seçerdin ve neden?",
    "İnsanların seni nasıl hatırlamasını istersin?",
    "Hayatında en bağlı olduğun şeyler neler?",
    "Hayatında en çok minnettar olduğun şey ne?",
    "Hayatta seni en çok zorlayan şey ne olmuştu? Bunun üstesinden nasıl geldin?",
    "Bir karar alırken mantığın mı yoksa duyguların mı daha çok ön planda olur? Neden?",
    "İnsanların senin hakkında yanlış anladığını düşündüğün bir şey var mı?",
    "Başka bir ülkede doğmuş olsaydın, hayatının nasıl farklı olacağını düşünüyorsun?",
    "Hayatında en çok pişmanlık duyduğun şey nedir? Ve bu seni nasıl etkiledi?",
    "Bir gün boyunca başka bir insanın bedeninde olsaydın, kimin bedeninde olurdun ve ne yapardın?",
    "Zamanı geri alma şansın olsaydı, hangi ana geri dönmek isterdin? Neden?",
    "En son ne zaman kendini tamamen mutlu hissettin? Bu anı ne özel kıldı?",
    "Hayatındaki en büyük başarı nedir? Bu başarıya ulaşmak için ne tür zorluklar yaşadın?",
    "Bir şeyde başarısız olacağından korktuğun için denemediğin bir şey var mı?",
    "Bir insanı derinden tanımak mı yoksa yüzeysel olarak birçok insanı tanımak mı daha önemli?",
    "Yapmayı çok isteyip de cesaret edemediğin bir şey var mı? Neden?",
    "Ölmeden önce mutlaka başarmak istediğin bir şey var mı?",
    "İnsanların çoğunlukla senin fark etmediği bir özelliğin nedir?",
    "Hayatında en çok kimin gözünde başarılı olmak istersin ve neden?",
    "Bir günlüğüne her istediğini yapabilme şansın olsa, günü nasıl geçirirdin?",
    "Kendini en çok hangi durumda kaybettiğini düşünüyorsun? Bu durumdan ne öğrendin?",
    "Bir insanı tanımadan önce bilmek istediğin en önemli özellik nedir?",
    "Üzgün anıları olan mutlu bir insan mısın yoksa mutlu anıları olan üzgün bir insan mı?"
        "Eğer rakibin kendin olsaydı ondan korkar mıydın?",
    "En sevdiğin ilk 3 dizi?",
    "En sevdiğin ilk filmin?",
    "%20 duyabilmek mi %40 görebilmek mi?",
    "En çok gurur duyduğun 2 özelliğin ne?",
    "Bir arkadaşını en son ne zaman gereksiz yere kırdın ve bu olayı tekrar yaşasaydın neyi farklı yapardın?",
    "Etrafındaki insanları kendi standartlarına göre mi değerlendiriyorsun yoksa onların koşullarını anlamaya mı çalışıyorsun?",


  ];

  static final List<String> coupleQuestions = [
    "Beni ilk görüşünde hakkımda ne düşündün?",
    "Bana karşı hislerin olduğunu ne zaman anladın?",
    "Beraber geçirdiğimiz en güzel anı neydi ve neden unutulmazdı?",
    "Birlikte yapmak istediğin en çılgınca şey nedir?",
    "Beni en çok hangi davranışım ya da özelliğimle seviyorsun?",
    "En sevmediğin özelliğim ne?",
    "Birlikteyken en çok hangi konularda anlaşmazlık yaşıyoruz ve bunu nasıl çözebiliriz?",
    "En çok sevgimi nasıl göstermemden hoşlanıyorsun ya da nasıl göstermemi isterdin?",
    "Aramızdaki bağın güçlendiğini düşündüğün bir an var mı?",
    "Beni ilk arkadaşlarına anlattığında ne söyledin?",
    "Hangi şarkı sana beni hatırlatıyor?",
    "Hafızan silindi ve benimle alakalı bir şeyi hatırlama hakkın var. Bu ne olurdu?",
    "Moralin bozukken yalnız olmak mı istersin yoksa yanında olmamı mı?",
    "Ben hafızamı kaybetsem bana söyleyeceğin ilk şey ne olurdu?",
    "Bir gün uyanıyorsun ve yaşadığımız her şey rüyaymış, dışarı çıkıyorsun yanımda başka biri var ne yapardın?",
    "İlişkide üstüne en çok düşündüğün sorun ne? Bunu nasıl düzeltebiliriz?",
    "Gelecekte birlikte gerçekleştirmek istediğin en büyük hayal nedir?",
    "İlk buluşmamızda en çok aklında kalan şey neydi?",
    "Eğer bir şeyde tamamen aynı fikirde olsaydık, bu hangi konuda olmasını isterdin?",
    "İlişkimizle ilgili seni en çok endişelendiren şey ne ve bu konuda nasıl bir çözüm bulabiliriz?",
    "Birbirimiz hakkında öğrendiğimiz en ilginç şey neydi?",
    "Birlikte gerçekleştirdiğimiz küçük ama seni en çok mutlu eden şey neydi?",
    "Eğer ilişkimize dair tek bir şeyi sonsuza kadar koruyabilsen, bu ne olurdu?",
    "Sence ilişkimizin en güçlü yönü nedir ve bunu nasıl daha da güçlendirebiliriz?",
    "İlişkimizle ilgili en gurur duyduğun an neydi?",
    "En sevdiğim renk ne?",
    "En sevdiğim yemek ne?",
    "En sevdiğim tatlı ne?",


  ];

  static final List<String> dateQuestions = [
    "Boş zamanlarında neler yapmaktan hoşlanırsın?",
    "En sevdiğin film veya dizi hangileri?",
    "Favori yemeğin ne?",
    "En sevdiğiniz müzik türü nedir?",
    "Son zamanlarda bir konsere veya etkinliğe gittin mi?",
    "Müzik aletleri çalmayı biliyor musun?",
    "Gelecekte gerçekleştirmek istediğiniz büyük bir hayalin var mı?",
    "Kendini üç kelimeyle nasıl tanımlarsın?"
        "Çocukluğunda en sevdiğin oyun veya aktivite neydi?",
    "En çok gurur duyduğun kişisel başarın ne?",
    "Arkadaşlarının seni en çok hangi yönünle tanımladığını düşünüyorsun?",
    "Hiç ilginç bir hobiye başladın mı, ama sonradan bırakmak zorunda kaldın mı?",
    "Hayatında bir dönüm noktası olarak gördüğün bir an var mı?",
    "Dünyada bir yeri ziyaret edebilseydin, neresi olurdu ve neden?",
    "En son izlediğin dizi/film seni nasıl etkiledi?",
    "Kendi başına bir şeyler yapmayı mı yoksa grup aktivitelerini mi daha çok seversin?",
    "Gelecek yıl hayatında neyin değişmiş olmasını umuyorsun?",

  ];

  static final List<String> selfKnowledgeQuestions = [
    "Hangi davranışlarım veya düşüncelerim beni ilerlemekten alıkoyuyor?",
    "Başarıyı neye göre değerlendiriyorum? Hangi başarılarımı yeterince takdir etmiyorum ve neden?",
    "Hangi deneyimler veya anılar şu anki kişiliğimi ve bakış açımı en çok etkiledi? Bu olaylar bana ne öğretti?",
    "Hangi eleştiriler veya durumlar beni savunmacı yapıyor? Bu savunmacılığın altında yatan sebepler neler?",
    "Hata yaptığımda veya zor zamanlar geçirdiğimde kendime nasıl davranıyorum?",
    "Kendimle ilgili hangi gerçekleri kabul etmekte zorlanıyorum? Bu gerçeklerle yüzleşmek bana ne kazandırabilir?",
    "Kendimi en çok hangi konularda sorumlu hissediyorum? Bu sorumluluklar beni nasıl olumlu veya olumsuz etkiliyor?",
    "Hayatımda en çok hangi değerlerime sadık kalıyorum ve bu değerler benim kararlarımı nasıl etkiliyor?",
    "Hayatımda hangi deneyimler bana en çok mutluluk getirdi ve bu deneyimleri nasıl daha sık yaşayabilirim?",
    "Kendime hangi alanlarda güveniyorum ve bu güveni nasıl kazandım?",
    "Kendimi başkalarıyla karşılaştırdığımda nasıl hissediyorum ve bu karşılaştırmalar beni nasıl etkiliyor?",
    "Başkalarının beklentileri beni ne kadar etkiliyor ve kendi yolumu daha özgürce nasıl çizebilirim?",
    "Şu anki yaşam tarzım gelecekteki hedeflerimle ne kadar uyumlu ve bu uyumu nasıl arttırabilirim?",
    "Başkalarının gözünde nasıl biri olarak tanımlanmak isterdim ve bu imajı nasıl oluşturabilirim?",
    "Geçmişimde hangi seçimlerimden dolayı pişmanım ve bu pişmanlıklarla nasıl başa çıkabilirim?",
    "Hayatımda en çok hangi insanlar benim gelişimime katkı sağladı ve bu ilişkileri nasıl sürdürebilirim?",
    "Başkalarının benim hakkımda ne düşündüğünü ne kadar önemsiyorum ve bu düşünceler hayatımı nasıl yönlendiriyor?",
    "Kendim için belirlediğim en büyük hedef nedir ve bu hedefe ulaşmak için şu anda ne yapıyorum?",
    "Hayatımda en çok hangi anlarda iç huzuru buluyorum ve bu huzuru nasıl artırabilirim?",
    "Şu an sahip olduğum alışkanlıklar beni istediğim yere götürüyor mu, yoksa geride mi tutuyor?",
    "Günlük hayatımda beni en çok zorlayan şeyler neler ve bu zorlukları nasıl daha kolay aşabilirim?",
    "En çok hangi anlarda kendimden şüphe duyuyorum ve bu şüphelerin kaynağı ne?",
    "Başarıya giden yolda en çok hangi küçük adımlar bana motivasyon veriyor?",
    "Hangi olaylar veya durumlar beni en çok duygusal olarak etkiliyor ve neden?",
    "Hayatımdaki değişimlerle nasıl başa çıkıyorum ve değişime daha açık olmak için ne yapabilirim?",
    "Başkalarına karşı ne kadar anlayışlıyım ve kendime karşı da aynı anlayışı gösterebiliyor muyum?",
    "Hayatımda daha fazla denge yaratmak için neleri değiştirmem gerekiyor?",
    "Kendimi daha özgün ve samimi bir şekilde ifade etmek için hangi adımları atmalıyım?",
    "Başkalarına en sık verdiğin tavsiye nedir ve bu tavsiyeyi kendine ne kadar uygulayabiliyorsun?",
    "Bugüne kadar en çok keşke dediğin şey neydi ve bu durum seni hala etkiliyor mu?",
    "Geçmişte en çok hangi konuda haksızlık yaşadığını düşünüyorsun ve bu haksızlık seni nasıl şekillendirdi?",
    "Hangi anlarda daha dürüst olabilirdin ama olmadın ve bu durum seni nasıl etkiledi?",
    "Kendi kendine konuşurken en çok hangi konuları dile getiriyorsun ve bu konular hayatını nasıl etkiliyor?",
    "Şu an hayatında en çok ihtiyaç duyduğun şey ne ve bu ihtiyacı nasıl giderebilirsin?",

  ];

  static List <String> YourOwnQuestions = [
    ""
  ];

  static List <String> FavouriteQuestions = [""];

}